name: Cypress Web Tests
on: [push]
jobs:
  cypress-run-external-web:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run external Web Tests
        uses: cypress-io/github-action@v4
        with:
          record: true,
          spec: cypress/e2e/web/external/*.ts
        env:
          CYPRESS_BASE_URL: http://the-internet.herokuapp.com
      - name: Upload recording videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
  cypress-run-local-web:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run local Web Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          record: true,
          spec: cypress/e2e/web/local/*.cy.ts
      - name: Upload recording videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
  playwright-run-external-web:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
